version : '3'

services:

    nginx:
        container_name: nginx
        build: ./nginx
        image: docker-server/nginx
        restart: always
        ports:
            - "8980:8980"
        volumes :
            - ./dogobesitytest:/srv/docker-server
            - ./log:/var/log/nginx
        depends_on:
            - django

    django:
        container_name: dajngo
        build: ./dogobesitytest
        image: docker-server/django
        restart: always
        command : uwsgi --ini uwsgi.ini
        volumes :
            - ./dogobesitytest:/srv/docker-server
            - ./log:/var/log/uwsgi
